#+title: darkman.el

This package provides seamless integration between [[https://darkman.whynothugo.nl][Darkman]] and [[https://gnu.org/software/emacs][Emacs]]
using the [[https://www.freedesktop.org/wiki/Software/dbus/][D-Bus]] protocol.

* Installation

#+begin_quote
In an effort to keep the instructions concise, portable and applicable
no matter the situation, this section will not list every possible
method through which you can install the package, only the most basic.
#+end_quote

Begin by cloning the repository:

#+begin_src sh
git clone --branch 0.4.0 https://github.com/grtcdr/darkman.el darkman
#+end_src

Next, add the package to your [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Libraries.html][load path]]:

#+begin_src emacs-lisp
(add-to-list 'load-path "darkman")
#+end_src

Finally, require the package like so:

#+begin_src emacs-lisp
(require 'darkman)
#+end_src

* Usage

In your =init.el= file, define which theme is associated with which
mode. By default, /modus-themes/ will be used, but we'll choose the
/tango/ variants in this example.

#+begin_src emacs-lisp
(setq darkman-themes '(:light tango :dark tango-dark))
#+end_src

You can also use =M-x customize-group darkman RET= to customize the
variable.

=darkman.el= can listen for any signals to change the theme without
requiring you to manually create any scripts. You can enable this
behavior by enabling the minor mode:

#+begin_src emacs-lisp
(darkman-mode)
#+end_src

You should not call =load-theme= in your configuration as
=darkman-mode= when enabled will do that for you, even on startup.

** Other functions

=M-x darkman-toggle= will toggle the mode of the Darkman service from
within Emacs.

Additionally, you can use the =darkman-get= and =darkman-set=
functions to manually get and set the mode of the service
respectively.

* Tips

** Working alongside the built-in safety features
:PROPERTIES:
:CUSTOM_ID: safety
:END:

=load-theme= is part of the =custom.el= library and it comes with
certain [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html][security features]] that you may regard as inconvenient, but
they're absolutely necessary to preserve the security of your
system. We have decided to work hand in hand with these pre-existing
safety mechanisms in favor of implementing our own.

Loading a theme that's never been loaded before will result in a
prompt which you must answer with a "yes" in order to use it; however,
that's not feasible when you're using [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html][Emacs as a Server]].

Problems will arise if the package is loaded too early during the
initialization phase, but you can [[https://github.com/grtcdr/darkman.el/pull/7#issuecomment-1422666665][delay it]] by activating the mode only
when the session has been fully initialized.

** Disabling existing themes

Emacs does not disable the current theme when another one is loaded by
default, this behavior may be annoying to some but we can advise
=darkman-set= (and by extension =darkman-toggle=) to take into account
these preferences of ours by evaluating the following:

#+begin_src elisp
(defadvice darkman-set (before no-theme-stacking activate)
  "Disable the previous theme before loading a new one."
  (mapc #'disable-theme custom-enabled-themes))
#+end_src

* Debugging

** Is D-Bus running?

Use your service manager to verify whether the service is running,
here's an example using =systemd=:

#+begin_src sh
systemctl status dbus
#+end_src

#+begin_example
● dbus.service - D-Bus System Message Bus
     Loaded: loaded
     Active: active (running)
#+end_example

** Is Darkman running?

Use your service manager to verify whether the service is running,
here's an example using =systemd=:

#+begin_src sh
systemctl status --user darkman
#+end_src

#+begin_example
● darkman.service - Framework for dark-mode and light-mode transitions.
     Loaded: loaded
     Active: active (running)
#+end_example

** Is Emacs built with D-Bus support?

Usually it is, unless you're building from source, in which case you
can verify whether or not Emacs was built with D-Bus support using
=C-h v system-configuration-features RET= which should list =DBUS=.

* Contributors

Hey (future-)contributors, your help means so much to me, whether it
be code, documentation, general advice or constructive feedback!

- Agustín Cisneros
- Aleksei Fedotov

* Citing

If your research involves this project in any way, you may cite it
like so:

#+begin_src bibtex
@misc{ab23darkman,
  author = {Aziz Ben Ali},
   title = {Seamless integration between Darkman and Emacs using the D-Bus protocol},
     url = {https://grtcdr.tn/darkman.el/},
    year = 2023
}
#+end_src
