#+title: darkman.el

This package provides seamless integration between [[https://darkman.whynothugo.nl][Darkman]] and [[https://gnu.org/software/emacs][Emacs]]
using the [[https://www.freedesktop.org/wiki/Software/dbus/][D-Bus]] protocol.

* Installation

#+begin_quote
In an effort to keep the instructions concise, portable and applicable
no matter the situation, this section will not list every possible
method through which you can install the package, only the most basic.
#+end_quote

Begin by cloning the repository:

#+begin_src sh
git clone --branch 0.4.0 https://github.com/grtcdr/darkman.el darkman
#+end_src

Next, add the package to your [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Libraries.html][load path]]:

#+begin_src emacs-lisp
(add-to-list 'load-path "darkman")
#+end_src

Finally, require the package like so:

#+begin_src emacs-lisp
(require 'darkman)
#+end_src

* Contributors

Whether it is code, documentation, advice and constructive feedback,
the following people have helped improve this software:

- Agustín Cisneros
- Aleksei Fedotov

#+begin_quote
We maintain a list of to-dos in =TODO.org=, which is best viewed from
[[https://grtcdr.tn/darkman.el/TODO.html][the website]] or inside Emacs. Pick something to work on if you'd
like to help improve this package.
#+end_quote  

* Citing

If your research involves this project in any way, you may cite it
like so:

#+begin_src bibtex
@misc{ab23darkman,
  author = {Aziz Ben Ali},
   title = {Seamless integration between Darkman and Emacs using the D-Bus protocol},
     url = {https://grtcdr.tn/darkman.el/},
    year = 2023
}
#+end_src
