#+TITLE: darkman.el

=darkman.el= seamlessly integrates [[https://darkman.whynothugo.nl][Darkman]] with [[https://gnu.org/software/emacs][Emacs]] using the D-Bus protocol.

* Installation

If you haven't already, begin by install these dependencies:
- =dbus=
- =darkman=

Now, clone the repository:

#+begin_src sh
git clone https://github.com/grtcdr/darkman.el darkman
#+end_src

Finally, add the package to the =load-path= and then require it like so:

#+begin_src elisp
(add-to-list 'load-path "darkman")
(require 'darkman)
#+end_src

* Usage

For =darkman.el= to work properly, the D-Bus and Darkman services
should be running.

** Automatically set the theme on startup

In your =init.el=, define which theme is associated with which mode,
by default =modus-themes= are used.

#+begin_src elisp
(setq darkman-themes '(:light tango :dark tango-dark))
#+end_src

Instead of manually configuring a theme, you should do it this way:

#+begin_src elisp
(load-theme (darkman-get-theme))
#+end_src

=darkman-get-theme= returns a theme based on the current mode and the
themes you specified in the =darkman-themes= variable.

** Automatically switch themes when the mode changes

=darkman.el= is able to listen to Darkman's signals and changes the
theme without requiring you to manually create any scripts, you can
enable this behavior by enabling the minor mode:

#+begin_src elisp
(darkman-mode)
#+end_src

Your themes will now be automatically changed as soon as Darkman
switches modes.

** Other functions

You can use =M-x darkman-toggle= to toggle the mode of the Darkman
service from within Emacs.

Additionally, you can use =(darkman-set MODE)= and =(darkman-get)= to
manually set and get the mode of the Darkman service respectively.

* Debugging

** Nothing's working?

*** Is D-Bus running?

Use your service manager to verify whether the service is running,
here's an example using =systemd=:

#+begin_src sh
systemctl status dbus
#+end_src

● dbus.service - D-Bus System Message Bus
     Loaded: loaded
     Active: *active* (running)

*** Is Darkman running?

Use your service manager to verify whether the service is running,
here's an example using =systemd=:

#+begin_src sh
systemctl status --user darkman
#+end_src

● darkman.service - Framework for dark-mode and light-mode transitions.
     Loaded: loaded
     Active: *active* (running)

*** Is Emacs built with D-Bus support?

Usually it is, unless you're building from source, in which case you
can determine whether or not Emacs was built with D-Bus support like
so:

#+begin_src elisp
(numberp (string-match "DBUS" system-configuration-features))
#+end_src

If non-nil, your Emacs /was/ built with D-Bus support.

* Citing

You may cite this project in your research like so:

#+begin_src bibtex
@misc{ABA:darkman,
  author = {Aziz Ben Ali},
   title = {Darkman integration with Emacs},
     url = {https://github.com/grtcdr/darkman.el},
    year = 2023
}
#+end_src
