#+TITLE: darkman.el

This package uses the D-Bus protocol to integrate [[https://darkman.whynothugo.nl][Darkman]] with Emacs.

* Installation

Begin by cloning the repository:

#+begin_src sh
git clone https://github.com/grtcdr/darkman.el darkman
#+end_src

Add the package to the =load-path= and then require it like so:

#+begin_src elisp
(add-to-list 'load-path "darkman")
(require 'darkman)
#+end_src

* Usage

** Automatically set the theme on startup

First, define which theme is associated with which mode (by default,
=modus-themes= are used) like so:

#+begin_src elisp
(setq darkman-themes '(:light tango :dark tango-dark))
#+end_src

Then, place this snippet in your configuration =init.el=:

#+begin_src elisp
(load-theme (darkman-get-theme))
#+end_src

=darkman-get-theme= returns a theme based on the current darkman mode
and the themes you specified in the =darkman-themes= variable.

** Automatically switch themes when the mode changes

=darkman.el= is able to listen to darkman's signals and changes the
theme without requiring you to manually create any scripts, you can
enable this behavior by enabling the minor mode:

#+begin_src elisp
(darkman-mode)
#+end_src

Your themes will now be automatically changed as soon as darkman
switches modes.

** Other functions

You can use =M-x darkman-toggle= to toggle the mode of the darkman service
from within Emacs.

Additionally, you can use =(darkman-set MODE)= to manually
specify the mode of the darkman service.

* Citing

You may cite this project in your research like so:

#+begin_src bibtex
@misc{ABA:darkman,
  author = {Aziz Ben Ali},
   title = {Darkman integration with Emacs},
     url = {https://github.com/grtcdr/darkman.el},
    year = 2023
}
#+end_src
