#+title: To-dos
#+todo: TODO(t) DOING(-) BUG(b) | FIXED(f) DONE(d)
#+tags: sug(s) help(h)
#+link: issue https://todo.sr.ht/~grtcdr/<repo>/%s

- Items tagged with =sug= are suggestions received from people from
  somewhere external to this repository. A tag immediately following
  =sug= represents the pseudonym of the person with the original
  suggestion.
- Items tagged with =help= are tasks we could use your help in
  accomplishing.

* TODO Extend ~darkman-themes~ with ~setopt~ support
Automatically reloading the current theme on evaluation of ~setopt~ does not
seem like a bad idea.  This requires configuring the ~:set~ property for the
customizable variable ~darkman-themes~.
* TODO Increase test coverage
This should help us catch the nasty bugs, though it'll be a challenge
to do it correctly given most of this package is state-dependent.  The
groundwork for test coverage has been laid with the addition of the
new build manifest.
* DONE Investigate breakages when using [[https://elpa.gnu.org/devel/spacious-padding.html][spacious-padding]] :help:
Here are some of the bugs I've encountered when ~darkman-mode~ and
~spacious-padding-mode~ are both enabled:
- Changing a theme may temporarily freeze Emacs
- On startup, the ~window-divider~ face, i.e. the borders that separate any
  adjacent windows use incorrect foreground and background attributes,
  =unspecified-fg= and =unspecified-bg=, respectively.
* DONE Write up a Texinfo manual as an Org document
We could use [[https://github.com/grtcdr/liaison/blob/main/doc/manual/liaison.org][this manual]] as a template.
* DONE ~load-theme~ is called twice when =ModeChanged= is signaled :help:
This leads to a theme transition that isn't very smooth. I have no
idea what might be causing this, but a peek into Darkman's source code
could be helpful.
* DONE Themes will sometimes switch infinitely :help:
This causes Emacs to go haywire. The first time this happened was a short time
after merging [[https://github.com/grtcdr/darkman.el/pull/5][#5]]. I can reproduce it, but I haven't yet understood what exactly
causes it to occur.

